const displayNames = {
    user: "Người dùng",
  role: "Vị trí",
  photo: "Hình ảnh",
  home: "Trang chủ",
  dashboard: "Bảng điều khiển",
  generalSettings: "Cài đặt chung",
  education: "Đào tạo",
  product: "Sản phẩm",
  service: "Dịch vụ",
  enquiry: "Câu hỏi",
  id: "Mã số",
  name: "Tên",
  account: "Tài khoản",
  profile: "Hồ sơ",
  userName: "Tên đăng nhập",
  password: "Mật khẩu",
  currentPassword: "Mật khẩu hiện tại",
  newPassword: "Mật khẩu mới",
  confirmationPassword: "Xác nhận mật khẩu",
  fullName: "Tên đầy đủ",
  roleName: "Chức vụ",
  description: "Mô tả",
  quantity: "Số lượng",
  startingAt: "Bắt đầu vào lúc",
  endingAt: "Kết thúc vào lúc",
  category: "Phân loại",
  normalizedTitle: "Tiêu đề không dấu",
  title: "Tiêu đề",
  status: "Tình trạng",
  groupName: "Tên nhóm",
  orderByField: "Trường sắp xếp",
  orderByAscending: "Thứ tự sắp xếp",
  searchByField: "Trường tìm kiếm",
  searchByContent: "Nội dung tìm kiếm",
  page: "Trang",
  resultsPerPage: "Kết quả mỗi trang",
  pageCount: "Số trang",
  resultsCount: "Số kết quả",
  results: "Kết quả",
  thumbnail: "Ảnh xem trước",
  thumbnailFile: "File ảnh xem trước",
  operation: "Thao tác",
  mainPhoto: "Ảnh chính",
  mainQuote: "Trích dẫn",
  aboutUs: "Về chúng tôi",
  whyChooseUs: "Vì sao chọn chúng tôi",
  ourDifference: "Sự khác biệt của chúng tôi",
  ourCulture: "Văn hoá của chúng tôi",
  members: "Đội ngũ",
  certificates: "Chứng chỉ",
  applicationName: "Tên trang web",
  applicationShortName: "Tên trang web (viết tắt)",
  favIcon: "Biểu tượng trang web",
  underMaintainance: "Tình trạng bảo trì",
  content: "Nội dung",
  photoFile: "File ảnh",
  course: "Khoá học",
  summary: "Tóm tắt",
  introduction: "Giới thiệu",
  introductionItem: "Giới thiệu",
  detail: "Chi tiết",
  index: "Thứ tự",
  sliderItem: "Trình chiếu ảnh",
  summaryItem: "Giới thiệu",
  post: "Bài viết",
  postCategory: "Chuyên mục bài viết",
  createdDateTime: "Tạo vào lúc",
  updatedDateTime: "Sửa vào lúc",
  views: "Lượt xem",
  isPinned: "Được ghim",
  isPublished: "Được xuất bản",
  statistics: "Thống kê",
  totalCategories: "Chuyên mục",
  totalPostCount: "Bài viết",
  totalPostViews: "Lượt xem",
  unpublishedPostCount: "Chưa xuất bản",
  phoneNumber: "Số điện thoại",
  zalo: "Zalo",
  zaloNumber: "Số zalo",
  email: "Địa chỉ email",
  address: "Địa chỉ",
  receivedDateTime: "Ngày nhận",
  isCompleted: "Đã hoàn thành",
  contact: "Thông tin liên hệ",
  workingHours: "Giờ làm việc",
  recordedDateTime: "Ghi nhận lúc",
  accessCount: "Lượt truy cập",
  guestCount: "Khách truy cập",
  type: "Phân loại",
  periodOfDayName: "Khung giờ",
  trafficByDate: "Truy cập theo ngày",
  trafficByHour: "Truy cập theo giờ",
  trafficByHourRange: "Truy cập theo khung giờ",
  trafficByDevice: "Truy cập theo thiết bị",
  todayAccessCount: "Lượt truy cập hôm nay",
  todayGuestCount: "Khách truy cập hôm nay",
  incompletedEnquiryCount: "Câu hỏi chưa giải đáp",
};

export function useDisplayNames() {
  return displayNames;
}